server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: _SITE_ROOT_/data/promtool/positions.yaml

clients:
  - url: _LOKI_URL_/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: _LOKI_LOG_/*_DOMAIN_.log
  pipeline_stages:
  - json:
      expressions:
        time: time_iso8601
        status:
        response_time: request_time 
        request_body:
        response_body:
  - json:
      expressions:
        method:
        json_rpc_id: id
      source: request_body
  - json:
      source: response_body
      expressions:
        error_code: error.code
  - template:
      source: error_code
      template: '{{add .error_code 100000}}'
  - pack:
      labels:
        - method
        - status
        - response_time
        - time
        - json_rpc_id
        - error_code
  - timestamp:
      format: RFC3339
      source: time
      
