server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: _SITE_ROOT_/data/promtool/positions.yaml

clients:
  - url: _LOKI_URL_/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: _LOKI_LOG_/*_DOMAIN_.log
  pipeline_stages:
  - json:
      expressions:
        time: time_iso8601
        status:
        request_time: 
        request_body:
        response_body:
  - json:
      expressions:
        method:
      source: request_body
  - match:
      selector: '{__path__=~".+"} |~ ".*error.*code[^\\d-]{2,5}-?\\d+"'      
      stages:
      - regex:
          expression: 'code[^\d-]{2,5}(?P<code>-?\d+)'
          source: response_body
  - labels:
      status:
      time:
      method:
      error_code: code
      response_time: request_time
  - timestamp:
      format: RFC3339
      source: time      
