#!/bin/bash
DIR=$(dirname $(realpath $0))
SITE_ROOT=$DIR
NODE_CONF_HTTP_TMPL=$DIR/http.d/local
NODE_CONF_TMPL=$DIR/http.d
TYPE=gateway
VAR=$DIR/vars

curl="/usr/bin/curl -sk"

if [ ! -d "$VAR" ]; then
	mkdir $VAR
fi

if [ -f "$SITE_ROOT/.env_raw" ]; then source $SITE_ROOT/.env_raw >/dev/null; fi
if [ -z "$MBR_ENV" ]; then
	echo "MBR_ENV not defined"
	exit 1
else
	if [ -f "$SITE_ROOT/.env.$MBR_ENV" ]; then source $SITE_ROOT/.env.$MBR_ENV >/dev/null; fi
fi

cd $DIR

echo $DIR >$VAR/SITE_ROOT
mkdir -p $DIR/tmp $DIR/logs $DIR/data

gw_show() {
	ls vars | while read key; do
		val=$(cat vars/$key | sed 's/\//\\\//g')
		echo "$key: $val"
	done
}

gw_geo() {
	PORTAL_URL=$(cat $VAR/PORTAL_URL)
	ZONE=$(cat $VAR/ZONE)
	ID=$(cat $VAR/ID)
	# TOKEN=$(cat $VAR/TOKEN)
	APP_KEY=$(cat $VAR/APP_KEY)
	IP="$($curl -L http://ipv4.icanhazip.com)"
	n=$(grep -o "\." <<<"$IP" | wc -l)
	if [ $n -ne 3 ]; then
		echo "Your IP is unknown"
		exit 1
	fi

	if [ -z "$IP" ]; then
		echo "Your IP is unknown"
		exit 1
	fi

	zone=$($curl \
		-H "Content-Type: application/json" \
		-H "Authorization: $APP_KEY" \
		"${PORTAL_URL}/mbr/$TYPE/${ID}/geo?ip=$IP" | jq .continent_code)
	zone=$(echo $zone | sed 's/\"//g')
	if [ -z "$zone" ]; then
		echo "Cannot detect zone from IP $IP"
	fi

	if [ "$zone" != "${ZONE}" ]; then
		echo "WARNING: Your IP $IP not in zone ${ZONE}"
	fi
}

gw_nodeinfo() {

	ID=$(cat $VAR/ID)
	APP_KEY=$(cat $VAR/APP_KEY)
	PORTAL_URL=$(cat $VAR/PORTAL_URL)

	$curl \
		-H "Content-Type: application/json" \
		-H "Authorization: $APP_KEY" \
		"$PORTAL_URL/mbr/$TYPE/$ID/info" >$VAR/RAW
	cat $VAR/RAW
	IP=$(cat $VAR/RAW | jq .geo.ip)
	if [ -z "$IP" ]; then
		echo $IP >$VAR/IP
	fi

}
gw_nodeverify() {

	ID=$(cat $VAR/ID)
	APP_KEY=$(cat $VAR/APP_KEY)
	PORTAL_URL=$(cat $VAR/PORTAL_URL)

	$curl \
		-H "Content-Type: application/json" \
		-H "Authorization: $APP_KEY" \
		"$PORTAL_URL/mbr/$TYPE/$ID/verify"
}

gw_register() {

	ID=$(cat $VAR/ID)
	APP_KEY=$(cat $VAR/APP_KEY)
	PORTAL_URL=$(cat $VAR/PORTAL_URL)
	$curl \
		-H "Content-Type: application/json" \
		-H "Authorization: $APP_KEY" \
		"$PORTAL_URL/mbr/$TYPE/$ID/register"

}
gw_unregister() {

	ID=$(cat $VAR/ID)
	APP_KEY=$(cat $VAR/APP_KEY)
	PORTAL_URL=$(cat $VAR/PORTAL_URL)
	$curl \
		-H "Content-Type: application/json" \
		-H "Authorization: $APP_KEY" \
		"$PORTAL_URL/mbr/$TYPE/$ID/unregister"

}
gw_set() {
	key="$1"
	val="$2"
	echo "$val" >"$VAR/$key"
	#node_apply

}
gw_get() {
	key="$1"
	cat "$VAR/$key"
	#node_apply

}
gw_keys() {
	ls "$VAR"
}
gw() {
	cmd=$1
	shift
	gw_$cmd $@
}
gateway() {
	cmd=$1
	shift
	gw_$cmd $@
}
node() {
	cmd=$1
	shift
	gw_$cmd $@
}
$@
