# version: "2"
services:
  gateway:
    privileged: true
    restart: unless-stopped
    # image: ubuntu:20.04
    image: massbitroute_gateway

    # command: 'sleep infinity'
    command: ""
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        BRANCH: keiko
    network_mode: "host"
    volumes:
      - ./logs:/massbit/massbitroute/app/src/sites/services/gateway/logs:rw
      - ./vars:/massbit/massbitroute/app/src/sites/services/gateway/vars:rw
    environment:
      - MBR_ENV=keiko
      - ID=
      - USER_ID=
      - BLOCKCHAIN=
      - NETWORK
      - ZONE=
      - APP_KEY=
      - INSTALL_CMD=
